name: Build Tweak
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          export THEOS=$HOME/theos
          git clone --recursive https://github.com/theos/theos.git $THEOS
          # Instala a ferramenta de assinatura que está faltando
          brew install ldid
          
      - name: Build Dylib
        run: |
          export THEOS=$HOME/theos
          make clean
          make FINALPACKAGE=1
          
      - name: Upload Result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: SensiInjetor-Dylib
          path: .theos/obj/arm64/*.dylib
