name: Build Tweak
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          export THEOS=$HOME/theos
          git clone --recursive https://github.com/theos/theos.git $THEOS
          mkdir -p $THEOS/sdks
          # Usando um link direto do repositório de SDks estáveis
          curl -L "https://github.com/theos/sdks/raw/master/iPhoneOS14.5.sdk.tar.xz" -o sdk.tar.xz
          # Verifica se o arquivo é realmente um dado compactado antes de extrair
          file sdk.tar.xz
          tar -xf sdk.tar.xz -C $THEOS/sdks
          rm sdk.tar.xz
          
      - name: Build Dylib
        run: |
          export THEOS=$HOME/theos
          make clean
          make FINALPACKAGE=1
          
      - name: Upload Result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: SensiInjetor-Dylib
          path: .theos/obj/arm64/*.dylib
